spring:
  datasource:
    url: jdbc:mysql://localhost:3306/login
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
  redis:
    host: localhost
debug: true